# Generated by Django 5.2.8 on 2025-11-21 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('instalado', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('volumen_m3', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacion', models.TextField(blank=True)),
                ('medidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='consumo_agua.medidor')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('medidor', 'fecha')},
            },
        ),
    ]
