# Generated by Django 5.2.8 on 2025-11-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(choices=[('HUMEDAD', 'Humedad'), ('TEMPERATURA', 'Temperatura')], max_length=30)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_hora', models.DateTimeField()),
                ('nota', models.TextField(blank=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='sensores.sensor')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
